


name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16
      - name: Set heap size
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: export NODE_OPTIONS="--max_old_space_size=4096"
      - name: Cypress install
        run: npm install --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          install: false
          build: npm run build
          start: npm start
