
name: Cypress Tests

on:
  pull_request:
    types: [opened]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16
      - name: Cypress install
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: npm install --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          install: false
          build: npm run build
          start: npm run develop-prod
          broswer: chrome
